### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by FiberJW** [apollographql/intellij-graphql#2]
How would I install this plugin for android studio? I'm trying to learn apollo-android and would love not to have to jump into VS code to do my Graphql edits and back into Android studio for my java code. Thanks!

**Comment by asiandrummer** [comment]
@datwheat - I'll submit a PR that I've been working with very soon. This plugin integrates [GraphQL Language Service](https://github.com/graphql/graphql-language-service) with the Grammar-Kit implementation of GraphQL syntax, and will provide a set of language support features (e.g. lint/validations, typeahead, go-to definition, and etc).

**Comment by datwheat** [comment]
Awesome! Thanks for your work!

**Comment by tasomaniac** [comment]
I was able to build this plugin and install it to Android Studio. Here are the steps I took. 

This project requires an older version of Gradle (version 4.2 and around).
You either need to have that installed globally or need to setup gradle wrapper. 

1. Check your gradle version by calling `gradle --version`
    - If this does not work at all or version is `>= 5.0`, move to step 2
    - If the version is around `4.2`, run `gradle assemble`
2. You need gradle wrapper setup. Find another Gradle project and copy `gradlew` and/or `gradlew.bat` files.
    - Make sure those are executable
    - Run `./gradlew assemble`
3. Once you have successful build, find the plugin at `build/distributions/GraphQL.zip`
4. Go to Android Studio -> Plugins -> Install plugin from disk..
